name: Documentation Report
description: Report an issue with documentation
labels:
  - needs_triage
  - docs

body:
  - type: markdown
    attributes:
      value: |
        **Thank you reporting an issue with Ansible Runner documentation.**

        If you are looking for community support, please visit
        the [Community guide](https://ansible.readthedocs.io/projects/runner/en/latest/community/)
        for information how to reach out to us.

  - type:
    attributes:
      label: Summary
      description: Describe the problem or suggestion with the documentation
      validations:
        required: true
