name: Feature Request
description: Suggest a new feature
labels:
  - needs_triage
  - enhancement

body:
  - type: markdown
    attributes:
      value: |
        **Thank you for suggesting a new feature for Ansible Runner.**

        If you are looking for community support, please visit
        the [Community guide](https://ansible.readthedocs.io/projects/runner/en/latest/community/)
        for information how to reach out to us.

  - type:
    attributes:
      label: Summary
      description: Describe the new feature and how it would be used.
      validations:
        required: true
